
== HiveMQ Authentication and Authroization Extension

== MyAuthenticator
The MyAuthenticator class contains the authentication logic

The JWKS url needs to be modified according to where keycloak is running and what your realm is. My keycloak is running on a virtual machine on port 8081 and my keycloak realm is called smartocean-testrealm, so that is why the value is: "http://158.39.77.107:8081/realms/smartocean-testrealm/protocol/openid-connect/certs";

The same applies to the EXPECTED_ISSUER variable

The Authenticator expects the JWT token (for a client) to contain a claim of type Audience with the value: hivemq-smartocean-testbroker, this can be modified by changing the EXPECTED_AUDIENCE variable

All the clients needs a allowed_topics claim that contains the topics a client is authorized to publish or subscribe to. The allowed_topics claim is added to the client in Keycloak and is of type Hardcoded claim, the value is a comma separated list of topics, for example: ["smartocean/weather1, smartocean, weather2"]. It supports both the + and # wildcards, for example: ["smartocean/+/temperature] or ["smartocean/#"].

MyAuthenticator expects the JWT token to be sent in the password field in the MQTT CONNECT message, for example:
connOpts.setUserName(clientId);
connOpts.setPassword(jwtToken.toCharArray());
if the password field is empty the authentication will fail.

== MyClientAuthorizer
Checks each topic in the allowed_topics claim of the client and if the topic matches the topic in the MQTT PUBLISH or SUBSCRIBE message, then the client is authorized to publish or subscribe to that topic. If there is no match, then the client is not authorized to publish or subscribe to that topic.

== MyExtensionMain
Starts and stops the extension, it registers the MyAuthenticator and MyClientAuthorizer in the extension start method and unregisters them in the stop method.

== MyAuthenticatorProvider
The MyAuthenticatorProvider is used to create an instance of the MyAuthenticator class, it is registered in the MyExtensionMain class.

== MyClientAuthorizerProvider
The MyClientAuthorizerProvider is used to create an instance of the MyClientAuthorizer class, it is registered in the MyExtensionMain class.

== Setup (Just used for the tests)
in the root of the project, I created a config.properties file, it contains all the clientID and clientSecrets used for client credential flow.

In this repository the config.properties file is just used in the HiveMQAuthTets to test authentication and authorization using both client credential flow and authorization code flow with PKCE.

The REDIRECT_URI needs to be specified here when using authroization code flow with PKCE for authentication.

These values are loaded in the HiveMQAuthTests using the config loader

examples:
Properties props = ConfigLoader.load();

String s1ClientId = props.getProperty("S1CLIENTID");
String s1ClientSecret = props.getProperty("S1CLIENTSECRET");

String clientId = props.getProperty("CLIENT_ID");
String redirectUri = props.getProperty("REDIRECT_URI");



Example config.properties file:
S1CLIENTID=sensor-1
S1CLIENTSECRET=VDno4ZQ6TTIlKyhe4KvGqFS7PKcGTFvb
S2CLIENTID=sensor-2
S2CLIENTSECRET=fR7oYedWdKckidUpvVwJxrvbEUcW6qMF
S4CLIENTID=sensor-4
S4CLIENTSECRET=2OY2wvWdi4xIifMs0w8wfqdEbAAzFAjc
CLIENT_ID=MQTT-user-client
REDIRECT_URI=http://localhost:8081/callback


The Config class contains the Realm and Base URL
final static String KEYCLOAK_REALM = "smartocean-testrealm";
final static String BASE_URL = "http://158.39.77.107:8081";

== Installation
Clone the repo into a Java 17 maven project

Run mvn clean package to build the extension

It builds a zip file in the target folder, for example:
C:\Users\vefje\IdeaProjects\HiveMQJWTAuthExtension1\target\HiveMQJWTAuthExtension1-1.0-SNAPSHOT-distribution.zip

go to: C:\Users\vefje\IdeaProjects\HiveMQJWTAuthExtension1\target

unzip the HiveMQJWTAuthExtension1-1.0-SNAPSHOT-distribution.zip

Attach the extension to HiveMQ using a volume mount

Running it locally example:
docker run -d --name hivemq ^
-p 8082:8080 ^
-p 1883:1883 ^
-p 9399:9399 ^
-e HIVEMQ_ALLOW_ALL_CLIENTS=false ^
-v "C:\Users\vefje\IdeaProjects\HiveMQJWTAuthExtension1\target\HiveMQJWTAuthExtension1-1.0-SNAPSHOT-distribution\HiveMQJWTAuthExtension1:/opt/hivemq/extensions/HiveMQJWTAuthExtension1"

Virtual machine example:
ubuntu@smartocean:~$ docker run -d --name hivemq \
-p 8082:8080 \
-p 1883:1883 \
-p 9399:9399 \
-e HIVEMQ_ALLOW_ALL_CLIENTS=false \
-v /home/ubuntu/extensions/HiveMQJWTAuthExtension1:/opt/hivemq/extensions/HiveMQJWTAuthExtension1









